version: "3.9"

networks:
  myblog:
    driver: bridge

services:
  hexo-build:
    container_name: hexo-build
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    command: ["generate", "--watch"]
    volumes:
      - ./:/app/
    hostname: hexo-build
    restart: always
    profiles: [dev]

  hexo-server:
    container_name: hexo-server
    build:
      context: .
      dockerfile: Dockerfile
    command: ["server", "-s"]
    volumes:
      - ./:/app/
    depends_on:
      - hexo-build
    hostname: hexo-server
    restart: always
    ports:
      - 4000:4000
    networks:
      - myblog
    profiles: [dev]
