
name: Build Action

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build_blog:
    permissions:
      contents: write
      security-events: write
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build Blog files
      - run: cd blog && npm install hexo-cli -g && npm install .
      - run: rm -rf blog/public
      - run: cd blog && hexo deploy

      - name: Deploy
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: blog
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
