name: Build Action

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build_blog:
    permissions:
      contents: write
      security-events: write
      actions: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build blog files
        run: npm install hexo-cli -g && rm -rf ./blog/public && cd blog && npm install . && hexo deploy

      - name: Copy workflow
        run: mkdir -p ./blog/public/.github/workflows/ && cp -r .github/workflows/*.yml ./blog/public/.github/workflows/

      - name: Deploy blog files
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: blog
          FOLDER: ./blog/public/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

