name: Build Action

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build_blog:
    permissions:
      contents: write
      security-events: write
      actions: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
      - uses: actions/checkout@v4

      - name: Use Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build Blog files
      - run: npm install hexo-cli -g
      - run: cd blog && npm install .
      - run: rm -rf blog/public
      - run: cd blog && hexo deploy
